### ISSUE TITLE
Outline should mention statistics and numerical analysis

### ISSUE THREAD

**Issue by pharpend** [learnmath/lysa#1]

**Comment by pharpend** [comment]
Also cryptography

**Comment by pharpend** [comment]
The consensus in the IRC channel seemed to be that we should discuss category theory as well.

**Comment by ghost** [comment]
category theory from the start.

**Comment by pharpend** [comment]
This issue should be moved to https://github.com/learnmath/learnmath.github.io

**Comment by pharpend** [comment]
[Moved](https://github.com/learnmath/learnmath.github.io/issues/4).

**Comment by pharpend** [comment]
I'm actually going to re-open this, with the additional condition that we should move the outline back over here.
