### ISSUE TITLE
LM Roman font

### ISSUE THREAD

**Issue by pharpend** [learnmath/lysa#11]
I don't know about the rest of you, but I really like the Latin Modern Roman font. It's the default font in LaTeX, and I think it would give our book an appropriate feel.

![If you aren't familiar with the font](http://cdn3.fontsquirrel.com/fnt_imgs/02/cf42/80798e40ca8861d8458e4481a0/para-202x200-12.png)

It's a very readable and handsome font.

**Comment by ghost** [comment]
Agreed.

**Comment by sarahzrf** [comment]
i like it but i'm not sure how tonally appropriate it is; it feels pretty formal.

**Comment by pharpend** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Meh, the serifed font is good because it's readable. It has little to do with
formality.

As far as serifed fonts go, LM Roman is one of the better fonts. Furthermore,
it's a standard font in math. If nothing else, it will serve as an inside joke.

Peter Harpending

On Fri, Dec 19, 2014 at 07:09:26PM +0000, benzrf wrote:

> i like it but i'm not sure how tonally appropriate it is; it seems pretty formal.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/learnmath/lysa/issues/11#issuecomment-67682376.
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v2

iQIcBAEBAgAGBQJUlJg5AAoJEMGyOuUw2xvm6c0P/0ujZwKKX0JpfiBVy2uGRqOK
EzL6d/ToHJ6RoqKoBG2xbZZmHmhoUGNHD8RIR01W1okj3LsY+qoV6m6PmN6XX+S+
nMwDngXT+9ofU7eyAiHwaHqsGH1TnSO0q0TH3WNuwKup7rPpvLSsUGlvEc6FN/ya
fUb4GT5j8sfTDlIlIol8mXGhLbEGNCt+3yMHN8q1JZgJdUlTgJsVkrRVo2iPo7LM
LFrPWmqgGdH3DE1Luu0SXCgQN6Y/CEbajZkqXAIAxI3YqTFH1n1MNedvrMc9zFlI
EigNrCktTA9kAUaKWTv1oreRwepWEVeiKQkY8JpSKchbV8/+lluCa9KasnQMAtQT
EdyU9iOBSLdYjxIKrEmjxwXEn/juWXXjnvWTJJ72cGYTfyOsN1DMkbvtSqBiQCfY
wscDTbsnOO8XXgoR3fq2zY/8Q/p7XLYZ/mp+w8ETc/5CK2tQofdDq5e1lBq/Mbkg
/ycDKl30UHvEH0u/8thMLRwTh1PvoRIAw+aIyh+yUoSXJUFEWj83YYHHztmbGcje
0QywESiNrVMQPiy10zehH7ryeQ3UyQAealaJ5A/yxbAB/VJsL0mbgP/w7G1nMZ6p
4OWkkJ31DP2dH8a3ia9uFNSIqHKrbZ0pZNuUyYb33hMvXpnA1aGDTaym7lSsQNir
JjTpp+68dcjk8nx0WAyE
=WALK
-----END PGP SIGNATURE-----

**Comment by pharpend** [comment]
I have the fonts (the otf files) in my branch:

https://github.com/pharpend/lysa/tree/feature/lmroman/site/fonts

I'm not sure how to use those OTF files in a stylesheet though. I'm not a CSS person.

**Comment by pharpend** [comment]
I managed to figure it out, I did some regex & wdired fu. You can see the results on my version of the site:

https://pharpend.github.io/lysa/

Here's the relevant stylesheet, if anyone's wondering how I did it:

https://github.com/pharpend/lysa/blob/feature/lmroman/site/stylesheets/default.sass

**Comment by pharpend** [comment]
So, it looks good, but there is a bit of a conflict, as the LM Roman font doesn't seem to go well with the default monospace font (Liberation, IIRC). 

![](https://i.imgur.com/pnRFjVd.png)

The next option would be to switch to the LaTeX monospace font, which I don't think looks very good:

![](https://i.imgur.com/hByU4oN.png)

I personally vote for Inconsolata:

![](https://i.imgur.com/93CwsyG.png)

**Comment by pharpend** [comment]
Assuming we go through with #12, this issue is moot, so I'm closing it.
