### ISSUE TITLE
Switch pack to PDF-based book?

### ISSUE THREAD

**Issue by pharpend** [learnmath/lysa#13]
Hi, y'all.

After about an hour of wrestling with the build script, I've decided to move to
scrap the website idea, and to develop the book as a PDF.

In theory. LaTeX can compile into HTML just fine. However, as I discovered
tonight, it's a pain in practice. Namely, it's very hard to do LaTeX macros on
the web. Macros are pretty much the entire point of LaTeX. Writing a LaTeX book
without macros would be like writing a huge program entirely in `main()`. It's
just awful for everybody.

Additionally, I think most of us care a lot about the content of the book, and
the format in which it is presented is secondary.  The reason I wanted to do the
web stuff was so we could have animated graphics. However, it occurs to me that
none of us are graphically competent enough to make animated graphics. Moreover,
the CC-SA license means that someone who is good at web stuff is free to take
the book and make it into a website.

With all that in mind, I vote to go back to PDF-based stuff, because that will
be easier for everybody.

I asked in the IRC channel, and everyone present in the conversation voted "Yes"
to the idea, with the exception of @darkf, who voted "Present".

**Comment by DTSCode** [comment]
sounds good.

**Comment by wei2912** [comment]
go ahead with it :)

**Comment by ghost** [comment]
I'm closing this issue since it's basically done.
