### ISSUE TITLE
Setup build system to deploy PDF files to a server

### ISSUE THREAD

**Issue by wei2912** [learnmath/lysa#15]
I have a bit of experience with Travis CI so I can probably do this, but I need a server to deploy to. A hackish way would be to create a repository with the PDF files (I assure you that this solution sucks). If a server is available, I'd rather upload the files there.

I'll also need admin access over the repository for this. If that isn't a good solution, perhaps someone else could do it.

**Comment by pharpend** [comment]
I'd be perfectly willing to give you admin access if it meant we could have regular PDF builds. I imagine @beingbrown agrees. On the off chance he doesn't agree, you could always deploy them yourself, and we'll just link to your thing.

I have a VPS, but it doesn't have an HTTP server or a domain name.

**Comment by ghost** [comment]
I'm beingbrown, and I agree with this message.

**Comment by pharpend** [comment]
Sponsored by the committee to elect beingbrown.

**Comment by wei2912** [comment]
Alright, I'll need admin access to this repository. The builds will be deployed to GitHub Releases, so I don't need access to a server. (They can be deployed to a server if needed, but for now I think GitHub Releases is suited for this).

**Comment by wei2912** [comment]
Here's the commit I made for `.travis.yml`:

https://github.com/wei2912/lysa/commit/6b9293bc5c81d3e63dfaa07352ee39eea0580d82

The language is set to C because having a C compiler around is always good (and because I can't set it to no language). The setup here uploads `book/lysa.pdf` which is the generated file. This will have to be changed accordingly for this repository.

For an example of a build, take a look at https://travis-ci.org/wei2912/lysa/builds/44809078. As you can see here, there're some dependencies that I have yet to install.

Travis CI will be able to build pull requests too, allowing people to check if the build of the book passes.

**Comment by wei2912** [comment]
Above links will no longer be valid. The branch is `build-system` and the builds can be seen at https://travis-ci.org/learnmath/lysa/.

**Comment by pharpend** [comment]
Alright, this is now done. Assuming #18 gets merged, we'll now have a little icon in the README.

@wei2912 There's some sort of error on the site, I think something is wrong with the .travis.yml file. I don't know, that's your thing. I'll let you fix it.

The build failure is a separate issue, so I'm closing this one.

**Comment by pharpend** [comment]
Okay, so I misunderstood. We now have automatic builds, but still no way to deploy them. Travis-CI will deploy the release for us if it's tagged, but we would have to tag things.There are 3 options:
1. Tag things nightly-ish and have travis work it's magic.
2. `scp` the resulting binaries over to some http server.
3. Deploy the nightlies on learnmath.github.io

Number 3 seems the least objectionable to me, as 1 will result in tag messes (and possibly collisions), 2 will just be a PITA (also we would have to get an http server). 3 is a bit annoying, but can be easily automated.

**Comment by pharpend** [comment]
To add on to my previous comment, now that @DTSCode is the site maintainer, I don't have much control over the lm.github.io site. Thus, whether or not option 3 is plausible is entirely at the discretion of @DTSCode .

**Comment by DTSCode** [comment]
What's option 3?
edit: ignore... apparently github doesnt email whole issue chains...
-----Original Message-----

**Comment by wei2912** [comment]
Option 3 is to deploy the nightlies on learnmath,github.io.

The problem with the options is that option 1 is a PITA to maintain, option 2 requires a http server (but is not as much of a PITA as option 1) and option 3 will result in pushing a lot of binaries into a Git repository (something we'll always want to avoid).

I like option 1 if it's possible to make it automatic, and option 2 if it's not. From my experience, binaries are the last thing you'll want in a Git repository.

**Comment by DTSCode** [comment]
I'll be giving @wei2912 my vps info that he can setup as a server for deployment

**Comment by DTSCode** [comment]
vote to close, since @wei2912 has a server to setup deployment for, and we are going for option 1

**Comment by wei2912** [comment]
Don't close this yet. I'll close it when I get the deployment up.

**Comment by DTSCode** [comment]
alright

**Comment by wei2912** [comment]
Deployment works successfully. https://travis-ci.org/learnmath/lysa/builds/44921537 I'll stop messing around with the `develop` branch.

Now, we'll need to setup Apache on @DTSCode's VPS.

**Comment by wei2912** [comment]
Builds can now be found at http://184.164.72.39/lysa/, annotated with the build number.

**Comment by pharpend** [comment]
Awesome. Thank you @DTSCode !
