### ISSUE TITLE
Can we switch over to the FDL?

### ISSUE THREAD

**Issue by pharpend** [learnmath/lysa#23]
We currently use the CC-SA license. I would like to switch to the GNU Free Documentation License, if that's okay with everybody.

The CC-SA license is a bit unclear on source redistribution. Namely, there's no requirement that "if you make changes, you have to give us those changes back in source form." For me, that's the entire point of the license. Instead, there's this:

> 1. The Adapter’s License You apply must be a Creative Commons license with the
>    same License Elements, this version or later, or a BY-SA Compatible
>    License.
> 2. You must include the text of, or the URI or hyperlink to, the Adapter's
>    License You apply. You may satisfy this condition in any reasonable manner
>    based on the medium, means, and context in which You Share Adapted
>    Material.
> 3. You may not offer or impose any additional or different terms or conditions
>    on, or apply any Effective Technological Measures to, Adapted Material that
>    restrict exercise of the rights granted under the Adapter's License You
>    apply.

which is not clear at all, and doesn't send the message across.

The GFDL, by contrast, is very clear on this:

> You may copy and distribute the Document in any medium, either commercially or
> noncommercially, provided that this License, the copyright notices, and the
> license notice saying this License applies to the Document are reproduced in
> all copies, and that you add no other conditions whatsoever to those of this
> License.  You may not use technical measures to obstruct or control the
> reading or further copying of the copies you make or distribute.  However, you
> may accept compensation in exchange for copies.  If you distribute a large
> enough number of copies you must also follow the conditions in section 3.
> 
> You may also lend copies, under the same conditions stated above, and you may
> publicly display copies.
> 
> If you publish or distribute Opaque copies of the Document numbering more than
> 100, you must either include a machine-readable Transparent copy along with
> each Opaque copy, or state in or with each Opaque copy a computer-network
> location from which the general network-using public has access to download
> using public-standard network protocols a complete Transparent copy of the
> Document, free of added material.  If you use the latter option, you must take
> reasonably prudent steps, when you begin distribution of Opaque copies in
> quantity, to ensure that this Transparent copy will remain thus accessible at
> the stated location until at least one year after the last time you distribute
> an Opaque copy (directly or through your agents or retailers) of that edition
> to the public.
> 
> It is requested, but not required, that you contact the authors of the
> Document well before redistributing any large number of copies, to give them a
> chance to provide you with an updated version of the Document.

The definition of transparent copy is also very clear

> A "Transparent" copy of the Document means a machine-readable copy,
> represented in a format whose specification is available to the general
> public, that is suitable for revising the document straightforwardly with
> generic text editors or (for images composed of pixels) generic paint programs
> or (for drawings) some widely available drawing editor, and that is suitable
> for input to text formatters or for automatic translation to a variety of
> formats suitable for input to text formatters.  A copy made in an otherwise
> Transparent file format whose markup, or absence of markup, has been arranged
> to thwart or discourage subsequent modification by readers is not Transparent.
> An image format is not Transparent if used for any substantial amount of text.
> A copy that is not "Transparent" is called "Opaque".
> 
> Examples of suitable formats for Transparent copies include plain ASCII
> without markup, Texinfo input format, LaTeX input format, SGML or XML using a
> publicly available DTD, and standard-conforming simple HTML, PostScript or PDF
> designed for human modification.  Examples of transparent image formats
> include PNG, XCF and JPG.  Opaque formats include proprietary formats that can
> be read and edited only by proprietary word processors, SGML or XML for which
> the DTD and/or processing tools are not generally available, and the
> machine-generated HTML, PostScript or PDF produced by some word processors for
> output purposes only.

The additional note about contacting us is good. The GFDL is basically exactly what _I_ want in the license. Is that okay with everybody / can I switch us over to the FDL?

Note that previous versions (i.e. those already in the commit history) will still be licensed under the CC-SA license, but new versions will be licensed under the GFDL.

**Comment by DTSCode** [comment]
Im fine with switching. I see no issue

**Comment by ghost** [comment]
I'm okay with switching.

**Comment by pharpend** [comment]
Alright, I'll close this as soon as #29 gets merged.

**Comment by pharpend** [comment]
Done.
