### ISSUE TITLE
List of roles in README

### ISSUE THREAD

**Issue by wei2912** [learnmath/lysa#24]
We should have a list of roles in the README so that people know who to contact for what.

Here's my current list:
- beingbrown -- project leader
- pharpend -- author
- jesyspa -- author
- DTSCode -- site maintainer
- wei2912 -- build system manager & quality control

**Comment by DTSCode** [comment]
Looks good. Two questions:
Is it tangentstorm not on this project?
Are we writing this up in the readme, along with emails and irc nicks?

**Comment by pharpend** [comment]
@DTSCode he's in the irc channel, but he hasn't done anything in the actual project (beyond starring the repo)

I suggested the readme, see #25 . We could put it in a separate file, or maybe in contributing.md, but I don't see why.

**Comment by pharpend** [comment]
I think I merged the PR, so I'm going to close this.
