### ISSUE TITLE
Contribution Guide should have an explanation of Travis

### ISSUE THREAD

**Issue by ghost** [learnmath/lysa#27]
The current working version of the contribution guide (https://github.com/beingbrown/lysa/blob/f-contributing/contributing.md) does not discuss Travis. Before merging, it needs an explanation of how to ensure successful builds.

**Comment by wei2912** [comment]
I'll work on it tomorrow.

**Comment by pharpend** [comment]
I agree, I barely even understand Travis-CI.

**Comment by wei2912** [comment]
I need to finish https://github.com/learnmath/lysa/issues/30 before I can work on this.

**Comment by ghost** [comment]
That's okay. @pharpend got me to go ahead and merge the contrib as is since travis is giving us trouble.

**Comment by wei2912** [comment]
I've written the contributing guide for Travis; please take a look at it and give some comments. :)

**Comment by pharpend** [comment]
It looks good! Thanks, @wei2912 !
