### ISSUE TITLE
Link to some actual sample content

### ISSUE THREAD

**Issue by pharpend** [learnmath/lysa#3]
People in the IRC channel seem to think that the entire book is jokes. Link to https://github.com/pharpend/lyaa/blob/master/chapters/ch0.tex to give people somewhat of an idea.

**Comment by pharpend** [comment]
Alright, I did this (at least my branch, which was merged). I'm not sure if we've pushed to gh-pages yet?

**Comment by ghost** [comment]
I've not had time yet to do any clean up on master. I'm looking forward to the break to really get started on this.
