### ISSUE TITLE
Travis-CI encryption key.

### ISSUE THREAD

**Issue by pharpend** [learnmath/lysa#30]
All of the builds that are in pull requests seem to be failing because of this error: 

```
$ scp -i deploy_rsa book/lysa.pdf $USER@$HOST:html/lysa-$TRAVIS_COMMIT.pdf

Enter passphrase for key 'deploy_rsa':

No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

This error looks like the key is encrypted and needs a passphrase to be decrypted. I would imagine the travis server has its own ssh key, couldn't you add that to the ~/.ssh/authorized_keys on @DTSCode's server? That way, we wouldn't need to provide our own key in the repo?

**Comment by wei2912** [comment]
The key that is decrypted relies on secret environment variables to
decrypt. For security reasons, Travis does not allow PRs to use these
secret variables to decrypt the key, as they can be printed and revealed.

A possible solution is to upload the file to a service that doesn't require
authentication.

**Comment by wei2912** [comment]
Fixed.

**Comment by pharpend** [comment]
Awesome, thanks.
