### ISSUE TITLE
lysa pdf name structure

### ISSUE THREAD

**Issue by ghost** [learnmath/lysa#37]
The pdf generator names pdfs with a number or what might be the commit value? anyway, maybe we can change the name structure so that they're in order of generation? date/timestamp make the most sense for this (until we can append a version number)?

![screenshot 2014-12-23 at 20 46 27](https://cloud.githubusercontent.com/assets/4888200/5545349/3450b13c-8ae5-11e4-8269-8a83cab54cc5.png)

**Comment by pharpend** [comment]
Correct me if I'm wrong, this seems to be a bug with @wei2912's build system, as opposed to @DTSCode's server. With that in mind, I'm assigning the issue to @wei2912. @wei2912, assign the issue to @DTSCode if it's not an issue on your end.

**Comment by wei2912** [comment]
The files with 2 digit numbers are build numbers, left over from the old system.

Right now, the naming scheme relies on commit hashes. The reason why I didn't use timestamps was because earlier builds are not guaranteed to terminate before later builds.

If you must sort by time, use `Last modified`. :)

**Comment by pharpend** [comment]
hmm. 

@DTSCode, maybe you could add something that does the ordering for us? Because an unsuspecting newbie is going to look there and just pick the latest one.

**Comment by wei2912** [comment]
Now that I think of it, a better naming scheme would be to use the Travis job number, which maintains correct order.

**Comment by pharpend** [comment]
Agreed.

**Comment by wei2912** [comment]
`master/` uses the tag specified by the committer (it will error out if there's no tag specified). All other branches will use the Travis build ID.

All builds are now in folders of their respective branches.
