### ISSUE TITLE
IRC bot for the channel

### ISSUE THREAD

**Issue by pharpend** [learnmath/lysa#4]

**Comment by pharpend** [comment]
For the time being, raylu's python bot works, because it can do math. Definitely would want an agda or coq bot.

**Comment by pharpend** [comment]
Also we have desbot now, which does logging and stuff

**Comment by ghost** [comment]
we can ask raylu if he doesn't mind temporarily keeping logs for us and kill desbot?

**Comment by pharpend** [comment]
I have my own personal logs (from keeping weechat open), I could just do a nightly dump of those.

**Comment by pharpend** [comment]
Just an update on this, I believe lambdabot is currently the only bot in the channel. I'm good with lambdabot, so I'm going to close this issue.
