### ISSUE TITLE
Add a specific thing for editors

### ISSUE THREAD

**Issue by pharpend** [learnmath/lysa#40]
@tangentstorm made a number of wonderful suggestions for improving the book, but he didn't actually commit any new content. For that reason, I would like to add a thing in the book about editors.

**Comment by pharpend** [comment]
https://github.com/pharpend/lysa/tree/f-editorthing contains a potential fix. Thoughts?

On another note, we ought to have an RFC system.

**Comment by wei2912** [comment]
What do you mean about adding a "thing in the book about editors"?

**Comment by pharpend** [comment]
@wei2912 some sort of mention between being (1) a full-on author and (2) not being mentioned at all. There's a potential fix on my branch, I meant to get your opinion on it last night.

**Comment by wei2912** [comment]
Looks quite fine to me, but perhaps you'd want to call them contributors instead? Since they're not exactly editors.

EDIT: Nvm, I see that in your [screenshot](https://i.imgur.com/bfpqg5w.png) you mention that these people are "Editors & Noted Contributors".

**Comment by pharpend** [comment]
@wei2912, you can actually embed screenshots, like this:

``` markdown
![Alt text](https://i.imgur.com/bfpqg5w.png)
```

![](https://i.imgur.com/bfpqg5w.png)

**Comment by wei2912** [comment]
I've always forgotten the format to do that.

Anyways, https://github.com/learnmath/lysa/pull/50 is merged, so closing this.
