### ISSUE TITLE
License should be in an appendix, not as a chapter.

### ISSUE THREAD

**Issue by wei2912** [learnmath/lysa#51]
As of build [45041239](http://dtscode.io/~lysa/develop/lysa-45041239.pdf), the license is placed in a chapter instead of as an appendix.

**Comment by pharpend** [comment]
I can make it a `\chapter*` which is an un-numbered chapter. Would that fix this?

**Comment by pharpend** [comment]
Okay, I figured out how to do appendices. For future reference, http://tex.stackexchange.com/questions/49643/making-appendix-for-thesis .

This will be solved once @beingbrown merges #69
