### ISSUE TITLE
travis bot for nightly builds only

### ISSUE THREAD

**Issue by ghost** [learnmath/lysa#70]
The bots in channel are overwhelming. Travis notifications should be embed into the merge page (don't merge before build is complete and passed), so we don't need to know if a build succeeds post merge--we should know that before hand. Is there a way to cut travis to only notify us of the pass/fail of nightly builds?

Related--travis build status is currently not active on the merge page, and this will need to be fixed in tandem.

**Comment by ghost** [comment]
@jesyspa brought up having the bot tell us if pull requests fail as well; I think this is a good idea. take the no news is good news approach.

**Comment by wei2912** [comment]
Are you suggesting that once we merge stuff in, Travis shouldn't build the
merged commit? Because there might be conflicts in the merged commit and
the develop branch that causes the build to fail.

**Comment by wei2912** [comment]
The no news is good news approach should be fine

**Comment by pharpend** [comment]
@wei2912, you are the resident Travis-CI zen master, so I'm assigning the issue to you.

**Comment by wei2912** [comment]
oooooommmmmmmmmm

**Comment by wei2912** [comment]
Okay, I have the bot set to only send out status messages if a build status changes.

**Comment by wei2912** [comment]
https://github.com/learnmath/lysa/pull/83

**Comment by pharpend** [comment]
I merged #83, hopefully this is fixed.

**Comment by ghost** [comment]
@wei2912 I'd still like prs built, but I don't need the notification in the channel--it's on the pr page that I have to look at to merge them, and prs are put in channel.

**Comment by pharpend** [comment]
@beingbrown Your grammar made your comment difficult to understand. Could you try again?

**Comment by ghost** [comment]
1) prs are posted in channel
2) travis builds prs and posts results on pr page
3) ergo, I don't need build notifications in channel

**Comment by wei2912** [comment]
I'll see if this is doable. It might not be, unfortunately, because I
didn't see any way to push notifications for builds.

**Comment by ghost** [comment]
@wei2912 I think this is how it's working now. I'll wait on your response before closing this.

**Comment by wei2912** [comment]
@beingbrown It appears that build state isn't tracked for PRs. As for commits to the main repository, the Travis bot will update us if the build status changes. Hence, this issue is resolved.

Thanks Travis for the unintentional side-effect.
