### ISSUE TITLE
Making the switch from learnmath.github.io to learnmath.io?

### ISSUE THREAD

**Issue by DTSCode** [learnmath/lysa#79]
Hi all! Tonite while I was at work, I got to thinking. I am not neccesarily what you would call a good web developer, and as a result I am struggling making a professional looking site in Jekyll. I can make a much better site in php, but obviously github and the rest of you don't want me using php, which I can understand. My solution: I buy a second vps, which would have the same plan as dtscode.io, and would setup the site on there using Facebook's hack lang, which doesn't seem to have any of the downsides of PHP. I would then buy the domain name learnmath.io, which i feel is good for us to have anyways, and point it to the vps. I would have no issues with buying either of these, as I have faith in this project, and now that the holidays are over, have money that I can dedicate for it. If none of you are comfortable with this, I understand, and would be perfectly fine with struggling through with jekyll. I look forward to hearing your feedback on this.

**Comment by pharpend** [comment]
I would be okay with buying learnmath.io and using that for the project.

My only concern is your choice of language. I personally would want something where another developer could easily take over were you to quit the project. Seeing as most of us know Haskell fairly well, and Haskell is a very nice language, I vote for Haskell. 

On the other hand, I am not particularly willing to maintain a website myself. Since you are willing to do that, I feel that it is your right to pick whatever language you want.

Wait for the opinion of @beingbrown before doing anything, though.

**Comment by wei2912** [comment]
@DTSCode is known to dislike Haskell greatly.

**Comment by pharpend** [comment]
@DTSCode can suck it.

**Comment by wei2912** [comment]
return PHP >>= @DTSCode >>= @pharpend  >>= Haskell

**Comment by pharpend** [comment]
``` haskell
(>=> fmap) . fmap traverse . traversed traverse . (<*> traverse)
  :: (Traversable ((->) (a1 -> f1 b1)), Traversable t1,
      Traversable t, Traversable f, Applicative f1) =>
     ((a1 -> f1 b1) -> (t1 a1 -> f1 (t1 b1)) -> a -> (a1 -> f1 b1) -> b)
     -> t a -> f (a1 -> f1 b1) -> f (f (t b))
```

**Comment by wei2912** [comment]
Shouldn't this issue be in `learnmath/learnmath.github.io`?  :stuck_out_tongue:

**Comment by pharpend** [comment]
Technically yes, but it will get more attention in here.

**Comment by DTSCode** [comment]
I don't dislike haskell :p just havent bothered learning it. and yes it should. my bad.

**Comment by ghost** [comment]
I know php well enough that if hack is remotely similar, I can deal with php. I'm a little concerned that you'd be putting a lot of money in @DTSCode ; why do we need a second vps? Or do you not want to host learnmath.io on the current one?

**Comment by DTSCode** [comment]
I think that's why I put it in here in the first place. I don't expect you guys to check website issues since you have enough on your plate

-----Original Message-----

**Comment by DTSCode** [comment]
Tbh @beingbrown the money I dedicate to the vps wouldn't be an issue. I'm not looking for reimbursement. The reason I don't want to host it on my current vps, was because I was hoping to host dtscode.io on it, among some other misc projects

-----Original Message-----

**Comment by ghost** [comment]
@DTSCode I'm sure we all appreciate the contribution; on your current vps, is memory or traffic the primary concern that causes you to want to split it off? I'm mostly concerned about whether or not it's needed; It sounds like you're already aware that you can host more than one site per vps, which I thought might have been the concern at first.

That said, I'm ++ to learnmath.io, and I'm ++ to you owning that url, as opposed to an org (org paperwork is so tedious) I don't think it's within my call to tell you how you go about setting that up (that is, how to spend your money). If you want it (or feel it needs to be) on a different vps than your personal projects, than that's your call to make.

don't forget to linke /r/learnmath on the site.

**Comment by pharpend** [comment]
I believe this is solved, so closing.
