### ISSUE TITLE
We ought to have a learnmath.github.io page

### ISSUE THREAD

**Issue by pharpend** [learnmath/lysa#8]
Currently we only have learnmath.github.io/lysa, we should have one for the project in general, not just the book.

**Comment by ghost** [comment]
Agreed. I guess we need a second repo for that?

**Comment by wei2912** [comment]
Sure, but for now it should be fine. If you wish to seperate the Hakyll
source from the generated website, refer to my repo blog_src.

**Comment by pharpend** [comment]
Oh well, apparently we do have an impromptu mailing list. I forgot github could do that.

@beingbrown And yes, we would need a second repo for that. Like @wei2912 said, it's not super important right now, but it could be in the future.

While we are at it, we should probably contact the /r/learnmath people on Reddit, just to avoid potential namespace conflicts should they ever decide to go to IRC.

**Comment by pharpend** [comment]
I suggested this in the channel, I don't know how many of you paid attention. Since #13, we've switched back to a PDF-based book. I suggested bisecting the develop branch in this repo, taking what used to be the website, and moving it to learnmath.github.io. LYSA could be one of our "hosted projects". This also opens the door to more "hosted projects", which would be nice.

**Comment by ghost** [comment]
+1

**Comment by pharpend** [comment]
Alright, this is done. Any issues with the website should be directed [here](https://github.com/learnmath/learnmath.github.io/issues/)
