### ISSUE TITLE
We need better issue flair

### ISSUE THREAD

**Issue by pharpend** [learnmath/lysa#88]
I'm thinking we ought to have separate issue flair for:
- IRC things (like #31, #4, #22)
- Community things (like #14, #87)
- Non-content-related book issues (like #15, #41, #69)
- Content-related issues (like #1) 

I'm not great at using GitHub's issue tracker, so I nominate @DTSCode or @wei2912 to solve the issue.

**Comment by wei2912** [comment]
I added the following flairs:
1. `irc` for anything related to IRC
2. `ministry of truth` for propaganda
3. `design` for non-content-related book issues
4. `content` for content-related book issues
5. `meta` for meta-stuff like this and https://github.com/learnmath/lysa/issues/82.

**Comment by wei2912** [comment]
There're quite a lot of labels right now. Perhaps we should clear some of them.

I plan on using colour coding to distinguish the labels.

EDIT: The category labels are marked in orange. Everything else remains the same colour.

**Comment by wei2912** [comment]
Additionally, there's an `in progress` label which complements the `help wanted` label.

EDIT: I grouped the labels as follows:
- Orange (category)
  - build-system
  - content
  - design
  - irc
  - meta
  - ministry of truth
- Red (attention needed)
  - bug
- Light Blue
  - enhancement
- Green (start)
  - help wanted
- Yellow (in progress)
  - in progress
- Grey (invalid)
  - duplicate
  - invalid
  - wontfix

**Comment by pharpend** [comment]
Okay, there are way too many labels for me to keep track. (This is not necessarily a bad thing). Someone else can deal with the labels =P. Anyway, this is fixed, so closing.

Thank you, @wei2912!
