### ISSUE TITLE
We need a better contributing guide & reading list

### ISSUE THREAD

**Issue by pharpend** [learnmath/lysa#9]
For now, the README sort of works.

We had a discussion in the IRC channel about this today.

I have some preliminary work on my branch
- https://github.com/pharpend/lysa/commit/cb4592fe3650b5e177d310d4a21076afbbc18834
- https://github.com/pharpend/lysa/commit/0e787329b1b766b30be896391738864d1ee8849e

Not even close to ready to be merged yet.

Apologies for brevity, I'm very sick and tired.

I'll probably be ready to do some real work on this on the weekend (or next week).

**Comment by ghost** [comment]
I'm working on changes to the contributing guide, which includes a walkthrough of forking, adding the remote to keep develop synced with lm:lysa, where conflict resolution should be resolved (hint: it's before a pull request is submitted), how to branch from and merge into develop, and how that process is different if making changes to gh-site. I do think a content creation guide is worth pursuing as well? (pull requests early and often--don't write forever and then submit a pull request; save all involved parties time).

**Comment by pharpend** [comment]
> (pull requests early and often--don't write forever and then submit a pull request; save all involved parties time)

I wrote a thing in the original README (not sure if it survived, it would be in the contrib guide now) about this. Basically it advised the potential contributor to ask about any substantial changes in the IRC channel, so that they don't end up doing a bunch of work and then have it end up being rejected.

I like your idea, though. If that thing I wrote still exists, probably add on to that.

**Comment by pharpend** [comment]
The first entry  in the math part of the reading list should be Edmund Landau's _Foundations of Analysis_, published by AMS Providence.

Our philosophy basically contains two points
1. Math books should be written in a manner that easy and fun to understand.
2. The math should nonetheless be taught in a logically rigorous and abstract matter.

The points somewhat go hand-in-hand. If you make math easier to understand, it's a lot easier to understand the abstractions, and vice versa.

The preface of Landau's book contains the following excerpt: (translated into English)

> ...Even one who studies mathematics mainly for its applications to physics and to other sciences, and who must therefore often discover auxiliary mathematical theorems for himself, can not continue to take steps securely along the path he has chosen, unless he has learned how to walk -- that is, unless he is able to distinguish between true and false, between supposition and proof.
> ...
> I therefore think it right, as do some of my mentors and colleagues, ... , that even in his first semester, the student should learn the basic facts from which mathematical analysis is developed, and how one can proceed with this development.
> ...
> Please forget what you learned in school; you haven't learned it.

There's more, but I'm too lazy to type it out. Nonetheless, that's a pretty good representation of the second point.

**Comment by pharpend** [comment]
I fixed some of the contributing guide in accordance with #13. The new contributing guide is included in #12. Note that the contributing guide merely mentions some software that is needed, does not mention anything about reading materials.

**Comment by pharpend** [comment]
Okay, #36 is merged, so this is slightly improved. We still need a reading list. I nominate @jesyspa .

**Comment by wei2912** [comment]
@pharpend Could we assign @jesyspa to this issue?

**Comment by pharpend** [comment]
Done.

**Comment by ghost** [comment]
Why don't we close this issue and open a new one for the reading list. one issue per issue?

**Comment by wei2912** [comment]
Sure, that'd be an excellent idea.

**Comment by pharpend** [comment]
@beingbrown One issue per issue? Apostasy!

...

Closing the issue.
